language: cpp
osx_image: xcode8.3
os:
  - linux
  - osx
git:
  depth: 50000
compiler:
  - gcc
dist: trusty
sudo: required
addons:
  apt:
    sources:
    - llvm-toolchain-trusty
    - llvm-toolchain-trusty-4.0
    - ubuntu-toolchain-r-test
    packages:
    - build-essential
    - gcc-6
    - g++-6
    - gcc-multilib
    - g++-multilib
    - gcc-6-multilib
    - g++-6-multilib	
    - linux-libc-dev
    - p7zip-full
    - clang-4.0
    - libc++-dev
    - libc++abi-dev
before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install p7zip; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-4.0 100; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang-4.0 100; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then export CC=clang; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then export CXX=clang++; fi
script: 
  - cd ./Build/
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then ./Build.Linux.sh; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then ./Build.MacOS.sh; fi
  - cd ./../
before_script:
  - if [ "$TRAVIS_TAG" == "" ]; then export MB_BUILD_VERSION=99.99; fi
  - if [ "$TRAVIS_TAG" != "" ]; then export MB_BUILD_VERSION=$TRAVIS_TAG; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then export MB_OS_NAME=Linux; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then export MB_OS_NAME=MacOS; fi
  - 7z a -tzip -r "MicroBuild-$MB_OS_NAME-$MB_BUILD_VERSION.zip" "Build" "Docs" "Plugins" "Source" "Tests" "LICENCE.md" "README.md"
after_success: 
  - 7z a -tzip -r "MicroBuild-$MB_OS_NAME-$MB_BUILD_VERSION.zip" "Binaries/$MB_OS_NAME/Shipping_x64/*"
  - 7z a -tzip -r "MicroBuild-$MB_OS_NAME-$MB_BUILD_VERSION.zip" "Binaries/$MB_OS_NAME/Shipping_x86/*"
deploy:
  provider: releases
  release: MicroBuild $MB_BUILD_VERSION
  description: "Release of version $MB_BUILD_VERSION of MicroBuild."
  name: MicroBuild $MB_BUILD_VERSION
  tag: $TRAVIS_TAG
  api_key: 
    secure: $GITHUB_TOKEN
  file: MicroBuild-$MB_OS_NAME-$MB_BUILD_VERSION.zip
  skip_cleanup: true
  on:
    tags: true
